# This file was generated by GoReleaser. DO NOT EDIT.
cask "azexempt" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "7cb94daffd4f798ff20f8dfc2ce72ee96e7a23a90f6f5c4dae04a1a955f38075"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_darwin_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
    on_arm do
      sha256 "8d77de83b8d35f31b61b590b19eb72fed4136438544b5f95ce784d99f9c997dd"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_darwin_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "507d7c43943559e70233bda3d2ebcf97564735c37fa2738d70bf826fb4bdd0de"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_linux_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
    on_arm do
      sha256 "a4a53e95279c7ac919f1c0c3bd98c86c35515b7a101d10b9c92df7c2f2941e71"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_linux_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
  end

  name "azexempt"
  desc "A TUI to easily create policy exemptions for customers in their environment"
  homepage "https://github.com/Lukas-Klein/azexempt"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azexempt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azexempt"]
    end
  end

  # No zap stanza required

end
