# This file was generated by GoReleaser. DO NOT EDIT.
cask "azexempt" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "fee6ff0d663fcee370a31cd4444d476242ec9db16a522b0bacf982551cc70d19"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_darwin_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
    on_arm do
      sha256 "b1b1ff403ae309a94fdcf11b8b2f27245fdacd12cd38f4ca292a973d9af6a7b7"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_darwin_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ea6011f0605f49038122ea8a1bad856e04640cf40b6bcab68f21f95c9dbd83f"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_linux_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
    on_arm do
      sha256 "4b7f3d041b3f8f24eb5852e12ca92609eff1cafc05014df5ac36916fd0d1a5f4"
      url "https://github.com/Lukas-Klein/azexempt/releases/download/v#{version}/azexempt_linux_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azexempt/releases/download"
    end
  end

  name "azexempt"
  desc "A TUI to easily create policy exemptions for customers in their environment"
  homepage "https://github.com/Lukas-Klein/azexempt"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azexempt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azexempt"]
    end
  end

  # No zap stanza required

end
