# This file was generated by GoReleaser. DO NOT EDIT.
cask "azure-exemption-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "de1ac32613f6869218455d4c324cb2fc6825cb54f0cd7531113aada694ff7116"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_darwin_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
    on_arm do
      sha256 "804c5dc0e33402351a3ddb669f138cba5d2a314dd4de048c270d8b29f973b749"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_darwin_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa106bbb05c7ee808f34840e1da1a81c419c423b645831d4346cb4a3d34d44b6"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_linux_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
    on_arm do
      sha256 "0298cf7ce868ffef4144690d6506b93a6cb70cacd6f2d5c3d09c14e1281923e2"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_linux_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
  end

  name "azure-exemption-cli"
  desc "A TUI to easily create policy exemptions for customers in their environment"
  homepage "https://github.com/Lukas-Klein/azure-exemption-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azure-exemption-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azure-exemption-cli"]
    end
  end

  # No zap stanza required

end
