# This file was generated by GoReleaser. DO NOT EDIT.
cask "azure-exemption-cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f7473a5f60b8824a81d487fffebec524a02b5b004f3a73fc38d25947d19c5528"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_darwin_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
    on_arm do
      sha256 "def56946273448c312097aec46880b2cac5b164faeb68eabec0098102c4e8add"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_darwin_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "83db4e38c4e06cfb2eeadde0a7ad33ed2b06e11d7ceebab6b6fbd3fc7c7f806c"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_linux_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
    on_arm do
      sha256 "8950068e8bc47a555624a05655a42c5ce20a383524575878d63beb53b9eb0b66"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_linux_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
  end

  name "azure-exemption-cli"
  desc "A TUI to easily create policy exemptions for customers in their environment"
  homepage "https://github.com/Lukas-Klein/azure-exemption-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azure-exemption-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azure-exemption-cli"]
    end
  end

  # No zap stanza required

end
