# This file was generated by GoReleaser. DO NOT EDIT.
cask "azure-exemption-cli" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "3c0200734fbe7bea0210b0a6beda9e103a5e52a125b835661f6215b7517861a0"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_darwin_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
    on_arm do
      sha256 "99f83a8a7af0d049783a9ba17d7a8a84e3769887e5c43b8583325a5eb686f0b9"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_darwin_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3df11bef37c97f0ede61fa2f6b70df0a517561eacee5d5659d72721588ba2fb"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_linux_amd64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
    on_arm do
      sha256 "c3f725f8be25abfdc6aa2af1fdf360b9dae5cb89b3d80fc407eac91cd7e4aa3e"
      url "https://github.com/Lukas-Klein/azure-exemption-cli/releases/download/v#{version}/azure-exemption-cli_linux_arm64.tar.gz",
        verified: "github.com/Lukas-Klein/azure-exemption-cli/releases/download"
    end
  end

  name "azure-exemption-cli"
  desc "A TUI to easily create policy exemptions for customers in their environment"
  homepage "https://github.com/Lukas-Klein/azure-exemption-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "azure-exemption-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/azure-exemption-cli"]
    end
  end

  # No zap stanza required

end
